### ISSUE TITLE
Failed in loading serial datasets

### ISSUE THREAD

**Issue by MKBird000** [dongxiexidian/COTM#1]
All went well after loading the seg_cont.dat and seg_comm.dat
Runs into "seg fault"  in loading subsequent content and comments
Forget to free mem or someth went wrong in mem allocation?
hope u got this fixed, thx

**Comment by YujieSong** [comment]
Same error

**Comment by dongxiexidian** [comment]
Sorry for that, maybe I just uploaded an older version.
I'll get it fixed soon.

**Comment by dongxiexidian** [comment]
When making another improvement of the COTM model, found the right one.
See the recent uploads, please.

**Comment by smallyangy123** [comment]
Cool
